# .circleci/config.yml
version: 2
jobs:
  build:
    working_directory: /root/ProjectEuler/tests   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.0.3                # image comes from Docker hub
    steps:
      - checkout
      - run:
          name: Install and Test this package
          command: julia -e 'using Pkg; Pkg.update(); Pkg.clone(pwd()); Pkg.build("tests"); Pkg.test("tests");'
